# 数据库配置
spring:
  datasource:
    druid:
      # 测试环境
      test:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.25.106.66:3306/information_schema?useSSL=false&characterEncoding=utf-8
        username: root
        password: Mysql_test@10666
      # 演示环境
      show:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/information_schema?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: 123456
mybatis:
  type-aliases-package: com.example.mysqlcheck.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

myconfig:
  dbName: smarttrader